### ISSUE TITLE
TODO: Stage tasks

### ISSUE THREAD

**Issue by RSS1102** [vegetables-school/send-relevant-comment-action#1]
获取pr下的相关issue或者pr issue_number。仅限本repo。
- [ ] 第一次提交的pr (titile,body)。
- [ ] 每次的commit (titile,body)。
- [ ] 代码review 的信息。
- [ ] 可能会出现这种问题(issues/42#issuecomment-1009592629)。
- [ ] 添加一个参数来区别是发送给 'all','issue', 'pr', (默认'all'）。
- [ ] 验证是本repo的issue或者pr。
- [ ] 发送评论

---
- [ ] 可能会出现 的Discussions  相关信息(padding)
